# -*- coding: utf-8 -*-
"""Scraping Tweets from Twitter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PuHSpFzu-Fd4fVbaE2rH5leiFYsIAldp
"""

# import tweepy
import tweepy as tw
# your Twitter API key and API secret
my_api_key = "vYnTjxjFWL471STe2HW2dERiN"
my_api_secret = "oTsvu8BI2rwxvzTge0xIreCTmcJJxxSESk7XINbQHvgsiibocG"
# authenticate
auth = tw.OAuthHandler(my_api_key, my_api_secret)
api = tw.API(auth, wait_on_rate_limit=True)

# setting up a search query
search_query = "#airtel -filter:retweets"

# get tweets from the API
tweets = tw.Cursor(api.search,
              q=search_query,
              lang="en",
              since="2019-01-01").items(500)
# store the API responses in a list
tweets_copy = []
for tweet in tweets:
    tweets_copy.append(tweet)

print("Total Tweets fetched:", len(tweets_copy))

import pandas as pd
# intialize the dataframe
tweets_df = pd.DataFrame()
# populate the dataframe
for tweet in tweets_copy:
    hashtags = []
    try:
        for hashtag in tweet.entities["hashtags"]:
            hashtags.append(hashtag["text"])
        text = api.get_status(id=tweet.id, tweet_mode='extended').full_text
    except:
        pass
    tweets_df = tweets_df.append(pd.DataFrame({'user_name': tweet.user.name,
                                               'user_location': tweet.user.location,\
                                               'user_description': tweet.user.description,
                                               'user_verified': tweet.user.verified,
                                               'date': tweet.created_at,
                                               'text': text,
                                               'hashtags': [hashtags if hashtags else None],
                                               'source': tweet.source}))
    tweets_df = tweets_df.reset_index(drop=True)
# show the dataframe
tweets_df.head()

tweets_df.shape

tweets_df

tweets_df.to_csv(r'/content/drive/MyDrive/college/sem7/FYP/tweets_dataset.csv')